import React from "react";
import type { Metadata } from "next";
import { Overpass_Mono, Courier_Prime } from "next/font/google";

import "./globals.css";
import Navbar from './components/Navbar'

const overpassMono = Overpass_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={overpassMono.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
