import React from 'react'

import { Roboto } from 'next/font/google'

import '@/common/styles/asl.scss'

const roboto = Roboto({
  adjustFontFallback: false,
  display: 'swap',
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
